### ISSUE TITLE
Eliminate RethinkDb class

### ISSUE THREAD

**Issue by cgarciae** [billysometimes/rethinkdb#18]
Move all methods as top-level functions so you can use the library like this
```dart
import `package:rethinkdb_driver/rethinkdb_driver.dart` as r;
```

**Comment by cgarciae** [comment]
Or atleast deprecate it with the `@deprecated` annotation.

**Comment by billysometimes** [comment]
This could potentially cause problems since dart doesn't allow a variable number of arguments for methods, we are abusing `nosuchmethod` for things like `rqlDo` and `object`. I don't *think* we can do that for top-level methods but I could be wrong.

I we could overcome this in a couple of ways, requiring arguments to be a list:
```dart
//list with 2 items, 2 args total
 add = await r.rqlDo([r.expr(11),r.expr(3)],(a,b)=>a+b);

//list of one item, 2 args total
isAdminMessage = await r.rqlDo([r.table('users').get(1).pluck('isAdmin')],(userIsAdmin)=>'User is an administrator!');
```

and I'm fairly sure we would have to move `Connection` and `Cursor` to entirely different libraries in order to avoid doing things like this:
```dart
r.connect(db: "test",port: 28015).then((r.Connection connection){
  listAllAuthors(connection);
});

void listAllAuthors(r.Connection conn){
  r.table("users").run(conn).then((r.Cursor cur){
    cur.forEach((var user){
      ...
    });
  });
}
```

instead we'd have to add more imports:
```dart 
  import 'package:rethinkdb_driver/rethinkdb_driver.dart' as r;
  import 'package:rethinkdb_driver/connection.dart';
  import 'package:rethinkdb_driver/cursor.dart';

...
```

**Comment by cgarciae** [comment]
Instead of being a function, it `rqlDo` could be a top level getter of an object of some class, and the function call would trigger a `noSuchMethod` for trying to call the `call` method. Example
```dart
SomeClass get rqlDo => new SomeClass();

class SomeClass{
  noSuchMethod(Invocation invocation) {...}
}
```
I like the idea of moving those to separate libraries.
