### ISSUE TITLE
What does filter return?

### ISSUE THREAD

**Issue by FaisalAbid** [billysometimes/rethinkdb#20]
For example take this method

   `var result = await Rdb.getRethink()
      .table(DBConfig.conversations).filter((convo) {
      return (convo("from").eq(from).and(convo("to").eq(to)))
      .or(convo("to").eq(from).and(convo("from").eq(to)));
    }).orderBy(Rdb.getRethink().desc("lastUpdated")).run(conn);`

from the examples doc it looks like it should return Cursor, but in this case it's returning a List<Map> which is fine, but this wasn't the case before.

I am on "2.0.1+1"

I remember 1.7 and it returns Cursor

**Comment by billysometimes** [comment]
In the example above, it is the orderBy that is causing a list to be returned instead of a cursor.

According to the rethinkdb documentation, ```filter``` always returns the same type on which it was called upon.

```orderBy ``` returns an array, unless it is an indexed orderBy, which must be run on a table or table_slice.

```dart
  table().filter() //returns cursor
 
  table().filter().orderBy(key) //returns list

  table().orderBy(key).filter()  //still returns list

  table().orderBy(key,{"index":key}).filter() //returns cursor

  table().filter().orderBy(key,{"index":key}) //throws an error for calling index orderby on a cursor.
```

Does that help?

**Comment by FaisalAbid** [comment]
Ah! Thank you!  Makes so much more sense.
