### ISSUE TITLE
Calling .filter on a large dataset causes {"t":16,"r":["Token 1 not in stream cache."],"n":[],"b":[]}

### ISSUE THREAD

**Issue by FaisalAbid** [billysometimes/rethinkdb#21]
It's not reproducible all the time, but basically 

net.dart 267 is where it goes crazy and crashes because _replyQueries is 0 but the response token is 1.

So the error is something like null doesn't have _cursor because _replyQueries[response.token] is null

Googled this and saw Rethink had a bug with webUI doing something similar, just to be sure I upgraded rethinkdb to the latest one but the error is still there. I can reproduce it 100% till I clear the table and try again, after which filter works again for a while then starts to throw this error again.

**Comment by FaisalAbid** [comment]
Fill up your table with 7k+ records. Then do a filter({"key":"val"}).

The exception will be 

https://gist.github.com/FaisalAbid/e1992fdb168d56a9a8cd

The query is  Cursor result = await Rdb.getRethink().table(DBConfig.users).filter({"email":email}).run(conn);

However, if you do

Rdb.getRethink().table(DBConfig.users).filter({"email":email}).limit(10).run(conn);

It works fine

**Comment by FaisalAbid** [comment]
It looks like 675 is the magic number. limit(675) will work fine, but anything above will throw that error.

**Comment by billysometimes** [comment]
Sorry about the slow response, currently there is a development branch that uses Streams instead of iterables for the  Cursor class.  It is much more simple and stable, and does not appear to have the same issue. I have tested with 36k records.

Today I will work on merging it into master and pushing it out to pub.

In the meantime, if you'd like to switch over to https://github.com/billysometimes/rethinkdb/tree/cursor-stream

you can check out all the convenient new features cursor will inherit from stream such as ```take()```, ```firstWhere()```, and so on.

**Comment by FaisalAbid** [comment]
Great! Thanks Billy, would be awesome to have it in master, big improvement. 

Keep up the solid work
